# Generated by Django 5.0 on 2024-02-02 18:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
